version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: insightdb
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: insight
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
